name: mapmory
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # image_picker: ^0.6.7+17
  percent_indicator: ^4.0.1
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  # logger: ^0.9.4
  # kakaomap_webview: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/image/tosun.png
    - assets/image/mapmoryTXT.png
    - assets/image/map.png
    - assets/image/bar3.png
    - assets/image/bar4.png
    - assets/image/bar5.png
  uses-material-design: true
  
  # fonts:
  #   - family: GmarketSansTTF
  #     fonts:
  #       - assets: assets/fonts/GmarketSansTTFBold.ttf
  #       - assets: assets/fonts/GmarketSansTTFLight.ttf
  #       - assets: assets/fonts/GmarketSansTTFMedium.ttf


